name: Android CI with Test Reporting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

# Define permissions to allow creating check runs
permissions:
  actions: read
  contents: read
  checks: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Android SDK using the correct action
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: google_apis
          components: platform-tools,build-tools-33.0.0

      # Step 4: Add platform tools to PATH using the recommended method
      - name: Add platform tools to PATH
        run: echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH

      # Step 5: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 6: Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: $ANDROID_SDK_ROOT
          key: ${{ runner.os }}-android-sdk
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      # Step 7: Create Gradle Directory
      - name: Create Gradle Directory
        run: mkdir -p ~/.gradle

      # Step 8: Enable Gradle Daemon
      - name: Enable Gradle Daemon
        run: echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties

      # Step 9: Download dependencies
      - name: Download Dependencies
        run: ./gradlew dependencies

      # Step 10: Build the project
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Step 11: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Step 12: List Unit Test Results (for debugging)
      - name: List Unit Test Results
        run: ls -la app/build/test-results/testDebugUnitTest/

      # Step 13: Upload Unit Test Artifacts
      - name: Upload Unit Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-artifacts
          path: |
            app/build/test-results/testDebugUnitTest/
            app/build/reports/tests/testDebugUnitTest/index.html

      # Step 14: Publish Unit Test Results with dorny/test-reporter@v1
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: app/build/test-results/testDebugUnitTest/*.xml
          reporter: java-junit
          list-tests: all
          fail-on-error: true

  instrumented-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
  
      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
  
      # Step 3: Set up Android SDK using the correct action
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: google_apis
          components: platform-tools,build-tools-33.0.0
  
      # Step 4: Add platform tools to PATH using the recommended method
      - name: Add platform tools to PATH
        run: echo "${ANDROID_SDK_ROOT}/platform-tools" >> $GITHUB_PATH
  
      # Step 5: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      # Step 6: Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: $ANDROID_SDK_ROOT
          key: ${{ runner.os }}-android-sdk
          restore-keys: |
            ${{ runner.os }}-android-sdk-
  
      # Step 7: Create Gradle Directory
      - name: Create Gradle Directory
        run: mkdir -p ~/.gradle
  
      # Step 8: Enable Gradle Daemon
      - name: Enable Gradle Daemon
        run: echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
  
      # Step 9: Download dependencies
      - name: Download Dependencies
        run: ./gradlew dependencies
  
      # Step 10: Build the project
      - name: Build with Gradle
        run: ./gradlew assembleDebug
  
      # Step 11: Install KVM and Configure Permissions
      - name: Install KVM and Configure Permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils cpu-checker
          sudo adduser $USER kvm
          sudo adduser $USER libvirt
          sudo systemctl enable libvirtd
          sudo systemctl start libvirtd
          sudo chown root:kvm /dev/kvm
          sudo chmod 660 /dev/kvm
          sudo apt-get install -y cpu-checker
          sudo kvm-ok
  
      # Step 12: Reload Udev Rules and Trigger Changes
      - name: Reload Udev Rules and Trigger
        run: |
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
  
      # Step 13: Set up and Run Instrumented Tests using Android Emulator Runner
      - name: Run Instrumented Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Nexus_4
          force-avd-creation: true
          emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load -gpu swiftshader_indirect
          disable-animations: true
          emulator-boot-timeout: 600
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew connectedDebugAndroidTest --continue
  
      # Step 14: Set up Firebase Credentials
      - name: Set up Firebase Credentials
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > $HOME/firebase_credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_credentials.json" >> $GITHUB_ENV
  
      # Step 15: List Instrumented Test Results (for debugging)
      - name: List Instrumented Test Results
        run: ls -la app/build/test-results/androidTest/connected/
  
      # Step 16: Upload Instrumented Test Artifacts
      - name: Upload Instrumented Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: instrumented-test-artifacts
          path: |
            app/build/test-results/androidTest/connected/
            app/build/reports/androidTests/connected/index.html
  
      # Step 17: Publish Instrumented Test Results with dorny/test-reporter@v1
      - name: Publish Instrumented Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Instrumented Tests
          path: app/build/test-results/androidTest/connected/*.xml
          reporter: java-junit
          list-tests: all
          fail-on-error: true


